[profile.default]
src = "src"
out = "out"
libs = ["lib"]

cache_path  = 'forge-cache'

gas_reports = ["cPort"]

optimizer = true
optimizer_runs = 30000

[fuzz]
runs = 2000
max_test_rejects = 2560000

[invariant]
runs = 50
depth = 250
fail_on_revert = false

# See more config options https://github.com/foundry-rs/foundry/tree/master/config